feat: добавить сервис статистики
Lex4509/java-explore-with-me pull request #1
Opened 2023-02-26 16:31 UTC by Lex4509

2023-02-27 09:20 UTC, sergeymamonov requested changes
Рекомендую избавиться от самописных конструкторов и заменить их аннотациями Lombok.

2023-02-27 09:20 UTC, sergeymamonov commented on stats/pom.xml
> +    <dependencies>
Лучше вообще никаких зависимостей не внедрять в родительском помнике.

2023-02-27 09:20 UTC, sergeymamonov commented on stats/stats-dto/src/main/java/dto/EndpointHitDto.java
> +    public EndpointHitDto(Long id, String app, String uri, String ip, LocalDateTime timestamp) {
Пользуйтесь аннотациями Lombok для конструкторов.

2023-02-27 09:20 UTC, sergeymamonov commented on stats/stats-server/src/test/java/ru/ewm/stats/StatsServerApplicationTests.java
> +class StatsServerApplicationTests {
Если тесты не планируете писать, то лучше удалить папку с тестами.

2023-02-27 09:20 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/controller/HitController.java
> +    private final String pattern = "yyyy-MM-dd HH:mm:ss";
Оформите как константу

2023-02-27 09:20 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/controller/HitController.java
> +        if (startDateTime.isAfter(LocalDateTime.now())) {
Лучше перенести валидацию в сервис.

2023-02-27 09:20 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/model/EndpointHit.java
> +@NamedNativeQuery(name = "ViewStatsDtos",
Лучше бы перенести запросы в класс репозитория. Логически им там самое место.

2023-02-28 21:27 UTC, Lex4509 commented
Спасибо за ревью) исправил по всем замечаниям

2023-03-01 21:07 UTC, sergeymamonov approved these changes

2023-03-01 21:07 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/controller/HitController.java
> +    public HitController(HitService hitService) {
Можно заменить аннотацией Lombok

2023-03-01 21:07 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/service/impl/HitServiceImpl.java
> +    static final String PATTERN = "yyyy-MM-dd HH:mm:ss";
Специально пропущен модификатор доступа? Например, private

2023-03-01 21:07 UTC, sergeymamonov commented on stats/stats-server/src/main/java/ru/ewm/stats/model/EndpointHit.java
> +public class EndpointHit {
Аннотации не нужно отрывать от класса.

2023-03-01 21:58 UTC, merged